[env]
AWS_CLI_AUTO_PROMPT = 'on-partial'
AWS_DEFAULT_REGION = 'us-west-2'
AWS_PROFILE = 'dev'
AWS_RETRY_MODE = 'adaptive'

EDITOR = "code -r"

RUST_WITHOUT = 'rust-docs'

[tools]
# AWS and Cloud Tools
awscli = "prefix:2"
terraform = "prefix:1"
terraform-docs = "prefix:0"
tflint = "prefix:0"
vault = "prefix:2"

# Kubernetes Tools
helm = "prefix:3"
krew = "prefix:0"
kube-linter = "prefix:0"
kubectl = "prefix:1"
kubectx = "prefix:0"
kubie = "prefix:0"

# Development Languages
golang = "prefix:1"
nodejs = "lts"
python = "prefix:3"

# Development Tools
bazel = "prefix:5"
bitwarden = "latest"
checkov = "prefix:3"
dasel = "prefix:2"
gitconfig = "latest"
glab = "latest"
hadolint = "latest"
jq = "latest"
mysql = "prefix:8.0"
tfsec = "latest"
yamllint = "latest"
yarn = "prefix:3"

# Python Tools
ruff = "latest"
uv = "latest"
