[env]
RUST_WITHOUT = 'rust-docs'

[tools]
amazon-ecr-credential-helper = "latest"
aws-sso = "latest"
awscli = "prefix:2"
bats = "prefix:1"
bitwarden = "latest"
bun = "latest"
fd = "latest"
gitconfig = "latest"
glab = "latest"
go = "prefix:1"
node = "lts"
opencode = "latest"
rtk = "latest"
terraform = "prefix:1"
terraform-docs = "prefix:0"
tflint = "latest"
vault = "prefix:2"

# Kubernetes Tools
helm = "prefix:3.16"
krew = "latest"
kube-linter = "latest"
kubectl = "prefix:1.32"
kubectx = "prefix:0.9"
kubie = "latest"

tfsec = "latest"
yamllint = "latest"
yarn = "prefix:4"

# Python Tools
ruff = "latest"
uv = "latest"


