#!/bin/bash
echo "$0"

if [ "$1" = "-force" ]; then FORCE_UPDATE=true; fi
function confirm {
  if [ "$1" ]; then _prompt="$1"; else _prompt="Are you sure"; fi
  _prompt="$_prompt [y/n] ?"

  # Loop forever until the user enters a valid response (Y/N or Yes/No).
  read -rs -k 1 "$_prompt " _response
  while 1; do
    case "${_response}" in
    [Yy][Ee][Ss] | [Yy]) # Yes or Y (case-insensitive).
      return 1
      ;;
    [Nn][Oo] | [Nn]) # No or N.
      return 0
      ;;
    *) # Anything else (including a blank) is invalid.
      ;;
    esac
  done
}

ASDF_UPDATE=true
ASDF_STATUS_FILE="$HOME/.asdf_updated"

# Look for a file with a recent date, where latest status of ASDF update can be shared across shell environments
# If not found, or older than 1 day, then set ASDF_UPDATE == true

# Check file exists
if [ -f "$ASDF_STATUS_FILE" ]; then
  # get today's date for reference
  TODAY="$(date -j +%Y%m%d)"
  #echo "Today is $TODAY"
  # check file modified date
  ASDFMOD=$(date -j -r "$ASDF_STATUS_FILE" +"%Y%m%d")

  # check if $ASDFMOD is $TODAY
  if test "$ASDFMOD" -eq "$TODAY"; then
    ASDF_UPDATE=false
  fi
fi

echo "ASDF was last updated on $(date -j -f "%Y%m%d" "$ASDFMOD" +"%m-%d-%y")"

if [[ $ASDF_UPDATE == true || $FORCE_UPDATE == true ]]; then
  echo -e "! $(date -u +"%Y-%m-%dT%H:%M:%SZ") Start ASDF maintenance." | tee -a "$ASDF_STATUS_FILE"
  pushd "$HOME" || exit # so that we're working with $HOME/.tool-versions

  echo -e "! $(date -u +"%Y-%m-%dT%H:%M:%SZ") asdf plugin update" | tee -a "$ASDF_STATUS_FILE"
  asdf plugin-update --all >>"$ASDF_STATUS_FILE"

  echo -e "! $(date -u +"%Y-%m-%dT%H:%M:%SZ") asdf install" | tee -a "$ASDF_STATUS_FILE"
  asdf install >>"$ASDF_STATUS_FILE"

  echo -e "! $(date -u +"%Y-%m-%dT%H:%M:%SZ") asdf latest" | tee -a "$ASDF_STATUS_FILE"
  asdf latest --all | tee -a "$ASDF_STATUS_FILE"

  echo -e "! $(date -u +"%Y-%m-%dT%H:%M:%SZ") Done." | tee -a "$ASDF_STATUS_FILE"
  popd || exit
else
  echo "ASDF was already updated today"
fi

# Truncate log to the last 1000 lines
echo -e "$(tail -1000 "$ASDF_STATUS_FILE")" >"$ASDF_STATUS_FILE"
