#!/bin/bash
alias k='kubectl'
alias kp='k get pods -n $n'
alias kx='kubectx'
alias kn='kubens'

# switch context
alias kx-k1inf='kubectx k1-infra'
alias kx-stage='kubectx sap-stage'
alias kx-prod='kubectx sap-prod'
